# This is a basic workflow that is manually triggered

name: Push to prod

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:


jobs:
  merge-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Fetching upstream
        run: git fetch --all --unshallow

      - name: Checkout prod
        run: |
          git checkout prod
          git pull origin prod

      - name: Merge main into prod
        run: git merge --ff-only origin/main
          
      - name: Pushing to prod
        run: git push origin prod
